### ISSUE TITLE
PROJECTS: [TODO] Level 1 programming katas 

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/tech-department#171]
Create a project that lists some basic katas that demonstrate flow control. if/else loops

Each kata should be in a file with its own name.

This should be introduces before unit testing. Just get peeps to print results to the console or standard out as appropriate

- [x] projects/basic-flow-control-katas in java #172
- [x] projects/basic-flow-control-katas in js #173 
- [x] projects/basic-flow-control-katas in python #174
- [x] projects/basic-flow-control-katas in kotlin?
