### ISSUE TITLE
Java week 6 syllabus: ready for action

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/tech-department#220]
- [x] update syllabus index page to reflect week 6 Java changes changes https://github.com/Umuzi-org/tech-department/issues/226

Plan: 
- NCIT 16: Thinking like a machine / Boolean algebra, logic
- NCIT 11: Test-driven development

- [x] topic/introduction to JUnit: https://github.com/Umuzi-org/tech-department/issues/227
- [x] workshop/live-code: demonstrate unit tests with intelliJ and JUnit. Q&A. Probably quite quick
- [x] project/animals part 2: Add tests to animals project https://github.com/Umuzi-org/tech-department/issues/164
- [x] topic/tdd revise for Java https://github.com/Umuzi-org/tech-department/issues/228
- [x] workshop/ live-code introduction to tdd : https://github.com/Umuzi-org/tech-department/issues/229
- [x] Update simple calc for Java https://github.com/Umuzi-org/tech-department/issues/109
- [x] topics/  java error handling https://github.com/Umuzi-org/tech-department/issues/232
- [x] topics java file io https://github.com/Umuzi-org/tech-department/issues/233
