### ISSUE TITLE
Java Week 7 syllabus: ready for action

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/tech-department#221]
- [x] update syllabus index page for week 7 Java https://github.com/Umuzi-org/tech-department/issues/235
- [x] Monday: workshop on Error Handling https://github.com/Umuzi-org/tech-department/issues/232
- [x] Tuesday: Password Checker project Due on Thurs https://github.com/Umuzi-org/tech-department/issues/112
- [x] Readings on file io https://github.com/Umuzi-org/tech-department/issues/233
- [x] Readings on Logging https://github.com/Umuzi-org/tech-department/issues/237
