### ISSUE TITLE
Java week 10 syllabus: Ready for action

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/tech-department#326]
- [x] collections and data structures project #356
- [x] collections and data structure topic #357
- [x] project string and number manipulation #358
